# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['temp', 'learn', 'categories', 'image', 'label', 'examples', 'intf', 'is_cat', 'classify']

# %% ../app.ipynb 5
import pathlib
temp = pathlib.PosixPath
pathlib.PosixPath = pathlib.WindowsPath



def is_cat(x): return x[0].is_upper()
learn = load_learner('model_dog-vs-cat')


# %% ../app.ipynb 7
categories =('Dog', 'Cat')

def classify(image):
    pred, adx, probs = learn.predict(image)
    return dict(zip(categories, map(float,probs)))
classify(im)

# %% ../app.ipynb 8
image = gr.inputs.Image(shape=(192,192))
label = gr.outputs.Label()
examples = ['data/dog (2).jpg', 'data/cat (2).jpg', 'data/dogcat2.jpeg']

intf = gr.Interface(fn=classify, inputs=image, outputs=label, examples= examples)
intf.launch(inline=False)
